<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(ProbeFramework)' != ''">$(ProbeFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <IlcDehydrate>true</IlcDehydrate>
    <StackTraceLineNumberSupport>true</StackTraceLineNumberSupport>
  </PropertyGroup>
</Project>
