<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>aot-atlas-binja</AssemblyName>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <OptimizationPreference>Speed</OptimizationPreference>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Atlas/Atlas.csproj" />
  </ItemGroup>
</Project>
