<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework Condition="'$(ProbeFramework)' != ''">$(ProbeFramework)</TargetFramework>
    <PublishAot>true</PublishAot>
    <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
    <StackTraceSupport>false</StackTraceSupport>
    <DefineConstants Condition="'$(ExcludeUnboxed)' != 'true'">$(DefineConstants);KEEP_UNBOXED</DefineConstants>
  </PropertyGroup>
</Project>
