<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>aot-atlas</AssemblyName>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Speed</OptimizationPreference>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Atlas/Atlas.csproj" />
  </ItemGroup>
</Project>
