<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(ProbeFramework)' != ''">$(ProbeFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IlcFoldIdenticalMethodBodies>false</IlcFoldIdenticalMethodBodies>
  </PropertyGroup>
  <ItemGroup><DirectPInvoke Include="__Internal" /></ItemGroup>
</Project>
